### ISSUE TITLE
Errata: Invalid arguments for group replication

### ISSUE THREAD

**Issue by titpetric** [wagnerjfr/mysql-group-replication-docker#5]
Looking at the MySQL 8 docs, none of the group replication options have `--loose` as an additional prefix. Consider dropping them / updating the materials to the latest mysql 8.0 version.

**Comment by wagnerjfr** [comment]
We have some few references on the internet to it, not in the MySQL 8 docs.
But trying to create GR following the same steps (with Docker) without `--loose`, doesn't seem to work.

**Comment by wagnerjfr** [comment]
Latest version is update on Medium Story:
**[Setting up MySQL Group Replication with Docker images](https://medium.com/@wagnerjfr/setting-up-mysql-group-replication-with-mysql-docker-images-f5eedd44fa2b)**

**Comment by wagnerjfr** [comment]
Latest version is update on Medium Story:
**[Setting up MySQL Group Replication with Docker images](https://medium.com/@wagnerjfr/setting-up-mysql-group-replication-with-mysql-docker-images-f5eedd44fa2b)**

**Comment by titpetric** [comment]
A paywall is not a good place for docs :)
